[platform]
platform = "others"

[print_control]
join_lottery = 0
return_lotteryresult = 0
danmu = 0
普通送礼提示 = false
弹幕 = false

[task_control]
# 清理即将过期礼物，请true之后一定要把紧随其后的room设置为真实房间号
clean-expiring-gift = false
clean-expiring-gift2room = 0
# 单位秒
set-expiring-time = 43200

silver2coin = false

# 自动投满佩戴勋章当日亲密度
send2wearing-medal = false

# 老接口兑换硬币为银瓜子
doublegain_coin2silver = false

# 输入数字 0-5 表示主站自动投币
givecoin = 0

[other_control]
# 保持连接状态，下次再登陆不会重复登陆，读取存储的cookie重用，如要密码登陆，请手动清除bilibili.conf里面的cookie
keep-login = true

# 默认监听房间号
default_monitor_roomid = 23058
